data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-tutorial-402918'
    dataset: retail
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: 1234
  api_key_secret: 1234